### ISSUE TITLE
请问fal_flash_dev结构体里的写入粒度控制.write_gran，是由上层实现的吗

### ISSUE THREAD

**Issue by cctv180** [RT-Thread-packages/fal#25]
const struct fal_flash_dev stm32_onchip_flash =
{
    .name = "stm32_onchip",
    .addr = 0x08004000,
    .len = 48 * 1024,
    .blk_size = 16 * 1024,
    .ops = {NULL, read, write, erase},
    .**write_gran = 8**
};
8 : 设置写粒度，单位 bit， 0 表示未生效（默认值为 0 ），该成员是 fal 版本大于 0.4.0 的新增成员。各个 flash 写入粒度不尽相同，可通过该成员进行设置，以下列举几种常见 Flash 写粒度：
nor flash: 1 bit
stm32f4: 8 bit
stm32f1: 32 bit
stm32l4: 64 bit
write_gran 我搜索过源码只有定义没有使用。
因为STM32H7 写入地址有对齐要求否则引发Error_Handler

**Comment by armink** [comment]
对的，write_gran 由底层提供，供上层使用
