### ISSUE TITLE
read/write/erase这三个高频接口能优化掉find吗？

### ISSUE THREAD

**Issue by geniusgogo** [RT-Thread-packages/fal#27]
https://github.com/RT-Thread-packages/fal/blob/e7d49be0f3594f81449da28e88cdbdd388ba50f5/src/fal_partition.c#L461

为什么需要每次去通过find操作获取设备，不能在上层做设备句柄备份吗？
这样可以避免每次的find操作导致的性能损失？

**Comment by Guozhanxin** [comment]
已经优化了：03d95ac6fd0167570f50b12b864904a49f702390
