### ISSUE TITLE
最小读写长度问题

### ISSUE THREAD

**Issue by camel5** [RT-Thread-packages/fal#5]
程序中的最小读写长度为1个字节(byte)，但STM32F0XX系列FLASH的最小读写长度是1个字（word），这样移植到F0就要做大量的修改。是否可以引入最先读写长度的定义去解决这个问题，比如我们可以定义最小读写长度是byte,word,dword.

**Comment by armink** [comment]
在 flash 函数里做些改进就行了，4 字节不对齐时，先从 flash 中读取原始数据，拼凑到未对齐的位置，传递到 Flash driver 里，这样行吗？

**Comment by armink** [comment]
issue 先关闭了，后续有问题再开启
